TylerConlee/slab

- main.go
- makefile
- sla/analyzer.go
- zendesk/api.go
This PR adds versioning using the Git commit hash, adds a makefile for easy building and adds a fix for #6.
> Fix the index out of bounds issue, add a makefile

- config/config.go
- slack/notify.go
Added an additional configuration option that allows `@here` notifications to be turned off for specific SLA levels. #9
> Added switch for @Mentions in notifications

- slack/api.go
- slack/notify.go
> updated notifications

- main.go
Added command line check for version as per #8.
> added flag check for version

- config/config.go
- main.go
- slack/rtm.go
Adds a configuration option to enable/disable the triager role, and lays the foundation for the Metadata struct
> Configurable triager

- .circleci/config.yml
- .gitignore
- config/config.go
- default-config.toml
- glide.lock
- glide.yaml
- main.go
- slack/callbacks.go
- zendesk/parser.go
- zendesk/parser_test.go
The biggest change is that all dependencies are now vendored through glide, meaning `glide install` will get everything up and running. The Circle config has been updated to reflect that. Also adds a fix for #42
> Add tests, resolve ticket acknowledge link, vendor dependencies

- server/server.go
- slack/messages.go
- slack/rtm.go
Addresses #27 and responds with version and server uptime.
> Added status update to slack response

- slack/messages.go
Attachments provide additional information, so adding the tickets through attachments to new tickets will provide additional context.
> Changed tickets to attachments

- slack/messages.go
- slack/rtm.go
Adds an unset command and sets the default triager to the Slack bot. Resolves #62
> Unset command

- .gitignore
- makefile
In order to build releases easier, added a new command for each OS within the makefile
> added build commands to makefile

- process.go
- slack/messages.go
- slack/rtm.go
@slab diag provides a private message with the current state of where slab is at by outputting the current Sent slice. Additional formatting may be necessary, and the command may benefit from additional data, but this is a start.
> Adds diagnostic message

- slack/messages.go
Attempts to fix the bug found in #94
> Type assert sent slice to NotifySent

- slack/messages.go
> Add colored notification levels

- process.go
- slack/messages.go
> added user to author spot in SLAmessage

- README.md
- slack/callbacks.go
- slack/messages.go
> update readme and remove dropdown for set

- README.md
- process.go
- slack/messages.go
- zendesk/api.go
Takes care of the TODO for getalltickets, and resolves issue with readme link.
> Updated readme and refactored getalltickets

- config/config.go
- config/plugins.go
- plugins/plugins.go
- plugins/twilio.go
- process.go
- slack/commands.go
- slack/messages.go
Before any reliance on a specific plugin is added, or any conditionals are used to turn plugins off, add the underlying structure for plugins and make sure that works
> Begin scaffolding plugins

- plugins/plugins.go
- plugins/twilio.go
- slack/commands.go
While there are some aspects to this code that are specific to Twilio, it's likely going to be a template moving forward for other plugins.
> Finish scaffolding for default plugin template

- config/plugins.go
- plugins/plugins.go
- plugins/twilio.go
Also, removed references to phone number in configuration.
> added additional logging

- zendesk/api.go
> added early returns for failed API calls

- config/config.go
- handler.go
- main.go
- server.go
- server/handler.go
- slack/wizard.go
This PR does not contain everything needed to run config wizard.
> added keycheck and removed variable configuration file

- datastore/reporting.go
- main.go
- process.go
Resolves open pg connections that cause too many connected clients
> move iteration to separate function, close db connections

- datastore/connect.go
- process.go
Have the DB close on each loop to avoid too many clients
> attempt to close connections per loop

- datastore/connect.go
- datastore/reporting.go
- main.go
- process.go
> Revert "close unnecessary postgres connections to avoid too many clients"

- glide.lock
- glide.yaml
- handler.go
- log/log.go
- slack/callbacks.go
First step in fixing dropped triage notifications
> update glide dependencies

- _plugins/config.go
- _plugins/plugins.go
- process.go
- slack/commands.go
- slack/messages.go
Move remainder of plugin code out of Slab Core
> Plugin cleanup

- _plugins/pagerduty.go
- _plugins/plugins.go
- _plugins/twilio.go
First crack with Tyler; unlikely to do much of anything yet, but Pagerduty work is started.
> initial pagerduty connection

- zendesk/api.go
First step towards finding dropped tickets
> added log message for logging nil next pages

- _plugins/pagerduty.go
Tests have been fixed on master; merged those changes in, cleaned up PagerDuty functions, added Demo function and removed Send function for now.
> merge upstream changes and clean up Pagerduty plugin
